### **What is Churn Rate?**

Churn rate (sometimes called attrition rate), in its broadest sense, is a measure of the number of individuals or items moving out of a collective group over a specific period. It is one of two primary factors that determine the steady-state level of customers a business will support.

**Customer Churn**

It is when an existing customer, user, subscriber, or any kind of return client stops doing business or ends the relationship with a company.

### **Types of Customer Churn –**

1. Contractual Churn : When a customer is under a contract for a service and decides to cancel the service e.g. Cable TV, SaaS.

2. Voluntary Churn : When a user voluntarily cancels a service e.g. Cellular connection.

3. Non-Contractual Churn : When a customer is not under a contract for a service and decides to cancel the service e.g. Consumer Loyalty in retail stores.

4. Involuntary Churn : When a churn occurs without any request of the customer e.g. Credit card expiration.


**Reasons for Voluntary Churn**

* Lack of usage
* Poor service
* Better price

### **Part 1 — Data Preprocessing**

**IMPORTING LIBRARIES**

In [ ]:
from tensorflow.keras.models import load_model

In [ ]:
import numpy as np

In [ ]:
import joblib

### **LOADING MODEL**

In [ ]:
nn_model = load_model("customer_churn.h5")

In [ ]:
nn_model

### **CUSTOMER DATA**

In [ ]:
customer_data = [850.0, 30.0, 2.0, 141040.01, 1.0, 1.0, 1.0, 5978.2, 0.0, 1.0, 1.0]

In [ ]:
customer_data = np.array([customer_data])

In [ ]:
customer_data 

array([[8.5000000e+02, 3.0000000e+01, 2.0000000e+00, 1.4104001e+05,
        1.0000000e+00, 1.0000000e+00, 1.0000000e+00, 5.9782000e+03,
        0.0000000e+00, 1.0000000e+00, 1.0000000e+00]])

In [ ]:
sc = joblib.load("scaler_churn.pkl")

In [ ]:
sc

StandardScaler()

In [ ]:
customer_data = sc.transform(customer_data)

In [ ]:
customer_data

array([[ 2.0584476 , -0.84593077, -1.04241787,  1.03971956, -0.91668767,
         0.64920267,  0.97481699, -1.64222473, -0.57946723,  1.73494238,
         0.91324755]])

### **Making Predictions**

In [ ]:
nn_model.predict(customer_data)

array([[0.03829369]], dtype=float32)

### **Conclusion**

Customer churn prediction is crucial to the long-term financial stability of a company. 